# gateway/Dockerfile (similar en los otros servicios)
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

RUN npm run build

CMD ["node", "dist/main.js"]
